sudo: false
language: node_js
node_js:
- '6'
env:
  global:
  - BROWSERSTACK_USERNAME: << USERNAME GOES HERE >>
  - BROWSERSTACK_ACCESS_KEY: << ACCESS KEY GOES HERE >>
  - SAUCE_USERNAME: << USERNAME GOES HERE >>
  - SAUCE_ACCESS_KEY: << ACCESS KEY GOES HERE >>
install:
- travis_retry npm install grunt-cli
- travis_retry npm install
script:
- grunt
- grunt intern:node --combined
- grunt intern:saucelabs --combined
- grunt remapIstanbul:ci
- grunt uploadCoverage
notifications:
  slack:
    secure: oh8TDBwSgIP+wzUpXJBE0TaQlGtQqdBYbDa9obrizQjk/hWEXGaPFYbBTnKH+5P7OgROlLbZLVcClsEjLgx+Cku8PFe6wkcTEwg/Ryxggl7MV0jgFfapdEeYrRUiMORUF16b3jSYpCM925V8nBmvxtsxOr4HwaJvG3UTRhBV7uDhUQqLxZ+V6n2WqnJeKuUE33E0VDyB0MUHXBr6Q+hgzooavxeVYDTzzxP15m2nwN/VuVXQXVkbl6N3vFLo+VIivYyNfp7cpKGpyYqlc/1PhN172xD5cNNclUtrYhcSfRci3zXWV5ZvX1hw/uRyJ6g3y5hpqdEKPg1Vt6DoCKYTKNaylAx5AAq+uv83US2C6TIw0NZHiTPQYCwp+syW3tUFJxOO2OLXQ2c0hyUIYdEp3mZbxryqukGQP2pC/4X/5Jj1YUav07YAG9/0RWGimLZL6in3CqnR5vGHIrWdXkFVOkE6C/50WZIOTW2fCynFdv0jZm4hq+maAAa5y6IFieVCWxNCahTiEvE5Dek8sfrdHfD3rQoA0m3is2kWb83Y8BrUvclIJuAnk0wKN9oMIuO9YijkCEirwcWNmbjPPYIE8M7xGp8y54NqfaY6CdP5vmAYC0VJUa6LKdjOqFrl7zwZrtppJ27gKrJ5O4zmMsLF0oKRhmsBYwelHuSfu0f2cJ0=
